### ISSUE TITLE
suggest to change this kind of project to be private

### ISSUE THREAD

**Issue by fenyiwudian** [choice-form/os-client#30]

**Comment by nightire** [comment]
The reason it requires to be public is that our CI environment doesn't support headless chrome, so it cannot pass the tests in this project. In this case, we use Travis CI to run all tests. Currently, Travis only supports the open sourced project with a free plan, and it doesn't matter to expose the source code ATM. Once we finished the primary goal, we will explore to find the way to support headless browser in our private CI server.
